### ISSUE TITLE
musicbrainz api doesn't work

### ISSUE THREAD

**Issue by joselops** [Flowrey/youtube-bz#32]
### Summary

Getting the error:
```
    def _lookup(self, entity_type: str, mbid: str) -> dict[str, Any]:
TypeError: 'type' object is not subscriptable
```

Any youtube-bz call produces the same error. Any ideas?

**Comment by Flowrey** [comment]
Hello, it's a bug due to the dict annotation, dict should have been wrote with an uppercase 'D', whoever this syntax is allowed since Python3.9.
If you update you're Python version this should work again.

**Comment by Flowrey** [comment]
It should be fixed with this PR !
I will release a new version soon.

**Comment by joselops** [comment]
Thanks a lot!!
